"""baseline schema

Revision ID: 2da43d0a4454
Revises: 
Create Date: 2026-08-06 14:37:43.737933

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql


revision: str = '2da43d0a4454'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('isbn', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('publisher', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category', sa.Enum('COMIC', 'STUDY_GUIDE', 'NOVEL', 'HUMANITIES', 'SOCIAL_SCIENCE', 'BUSINESS_ECONOMICS', 'SCIENCE_TECHNOLOGY', 'CHILDREN', 'LANGUAGE', 'ART_LIFESTYLE', name='bookcategory'), nullable=False),
    sa.Column('standard_size', sa.Enum('A5', 'B5', name='standardsize'), nullable=True),
    sa.Column('thickness_mm', sa.Integer(), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('virtual_stock', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isbn')
    )
    op.create_table('fds_policies',
    sa.Column('policy_key', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('policy_value', sa.Numeric(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('policy_key')
    )
    op.create_table('inbound_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('inbound_type', sa.Enum('NEW_STOCK', 'USED_PURCHASE', 'CUSTOMER_RETURN', name='inboundtype'), nullable=False),
    sa.Column('status', sa.Enum('RECEIVED', 'CHECKING', 'COMPLETED', name='inboundstatus'), nullable=False),
    sa.Column('supplier_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('zone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rack', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('shelf', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('barcode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("barcode = zone || '-' || rack || '-' || shelf", name='ck_locations_barcode_components'),
    sa.CheckConstraint("rack ~ '^[1-9][0-9]*$'", name='ck_locations_rack_positive_integer'),
    sa.CheckConstraint("shelf ~ '^([1-9]|10)$'", name='ck_locations_shelf_range'),
    sa.CheckConstraint("zone IN ('A', 'B', 'C')", name='ck_locations_zone'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode')
    )
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('customer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type', sa.Enum('B2B_ORDER', 'AUTO_PO', name='ordertype'), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PICKING', 'SHIPPED', 'RETURN_REQUESTED', 'RECEIVED', name='orderstatus'), nullable=False),
    sa.Column('logistics_center', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('waybill_number', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('shipping_carrier', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('shipped_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_waybill_number'), 'orders', ['waybill_number'], unique=True)
    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_code'), 'tenants', ['code'], unique=True)
    op.create_table('weekly_insights',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('report_week', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('saved_labor_cost_krw', sa.Integer(), nullable=False),
    sa.Column('top_defective_publishers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('location_hotspots', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('logistics_hotspots', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('predicted_returns', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_week')
    )
    op.create_table('fds_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('fraud_score', sa.Integer(), nullable=False),
    sa.Column('fraud_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fds_reports_tenant_id'), 'fds_reports', ['tenant_id'], unique=False)
    op.create_table('inbound_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('inbound_job_id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('lpn_barcode', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('certificate_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('condition_grade', sa.Enum('MINT', 'EXCELLENT', 'NORMAL', 'REJECT', name='conditiongrade'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['inbound_job_id'], ['inbound_jobs.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('certificate_token'),
    sa.UniqueConstraint('lpn_barcode')
    )
    op.create_table('inventory',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reserved_quantity', sa.Integer(), nullable=False),
    sa.Column('discount_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('sale_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(discount_rate IS NULL) = (sale_price IS NULL)', name='ck_inventory_pricing_pair'),
    sa.CheckConstraint('discount_rate IS NULL OR (discount_rate >= 0 AND discount_rate < 1)', name='ck_inventory_discount_rate'),
    sa.CheckConstraint('reserved_quantity <= quantity', name='ck_inventory_reserved_quantity_not_exceed_quantity'),
    sa.CheckConstraint('reserved_quantity >= 0', name='ck_inventory_reserved_quantity_non_negative'),
    sa.CheckConstraint('sale_price IS NULL OR sale_price > 0', name='ck_inventory_sale_price_positive'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'location_id', name='uq_inventory_book_location')
    )
    op.create_table('inventory_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_type', sa.Enum('INBOUND', 'OUTBOUND', 'RETURN_RESTOCK', 'DISCARD', name='inventorytransactiontype'), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('condition_grade', sa.Enum('MINT', 'EXCELLENT', 'NORMAL', 'REJECT', name='conditiongrade'), nullable=True),
    sa.Column('quantity_change', sa.Integer(), nullable=False),
    sa.Column('target_lpn', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('picked_location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('FDS_ALERT', 'AGENT_ALERT', 'RESTOCK_ALERT', name='notificationcategory'), nullable=False),
    sa.Column('severity', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='notificationseverity'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=True),
    sa.Column('condition_grade', sa.Enum('MINT', 'EXCELLENT', 'NORMAL', 'REJECT', name='conditiongrade'), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('final_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('MASTER', 'ADMIN', 'WORKER', 'GUEST', 'PENDING', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='userstatus'), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('refresh_token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('refresh_token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('auth_version', sa.Integer(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token_hash')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_employee_id'), 'users', ['employee_id'], unique=True)
    op.create_index(op.f('ix_users_refresh_token_expires_at'), 'users', ['refresh_token_expires_at'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('board_posts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('NOTICE', 'MANUAL', 'GENERAL', name='postcategory'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attachment_paths', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_recipients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('notification_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notification_id', 'user_id', name='uq_notification_recipient')
    )
    op.create_index(op.f('ix_notification_recipients_notification_id'), 'notification_recipients', ['notification_id'], unique=False)
    op.create_index(op.f('ix_notification_recipients_read_at'), 'notification_recipients', ['read_at'], unique=False)
    op.create_index(op.f('ix_notification_recipients_user_id'), 'notification_recipients', ['user_id'], unique=False)
    op.create_table('order_item_inventory_allocations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_item_id', sa.Uuid(), nullable=False),
    sa.Column('inventory_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('picked_quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('picked_quantity >= 0 AND picked_quantity <= quantity', name='ck_order_item_inventory_allocation_picked_quantity'),
    sa.CheckConstraint('quantity > 0', name='ck_order_item_inventory_allocation_quantity_positive'),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_item_id', 'inventory_id', name='uq_order_item_inventory_allocation')
    )
    op.create_index(op.f('ix_order_item_inventory_allocations_inventory_id'), 'order_item_inventory_allocations', ['inventory_id'], unique=False)
    op.create_index(op.f('ix_order_item_inventory_allocations_order_item_id'), 'order_item_inventory_allocations', ['order_item_id'], unique=False)
    op.create_table('return_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('inbound_item_id', sa.Uuid(), nullable=True),
    sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mode', sa.Enum('RETURN', 'USED_PURCHASE', name='inspectionmode'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'APPROVED', 'REJECTED', 'HITL_REQUIRED', 'RECHECK_REQUIRED', 'FAILED', name='returnjobstatus'), nullable=False),
    sa.Column('image_paths', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ubci_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('condition_grade', sa.Enum('MINT', 'EXCELLENT', 'NORMAL', 'REJECT', name='conditiongrade'), nullable=True),
    sa.Column('agent_logs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('final_report', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ai_inspection_started_at', sa.DateTime(), nullable=False),
    sa.Column('ai_inspection_completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['inbound_item_id'], ['inbound_items.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_return_jobs_tenant_id'), 'return_jobs', ['tenant_id'], unique=False)
    op.create_table('boards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('ticket_status', sa.Enum('TODO', 'IN_PROGRESS', 'RESOLVED', name='ticketstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['return_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_used_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('return_job_id', sa.Uuid(), nullable=True),
    sa.Column('lpn_barcode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ubci_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('discount_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('sale_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('condition_grade', sa.Enum('MINT', 'EXCELLENT', 'NORMAL', 'REJECT', name='conditiongrade'), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'RESERVED', 'SHIPPED', name='usedinventorystatus'), nullable=False),
    sa.Column('certificate_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stocked_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("condition_grade IN ('MINT', 'EXCELLENT', 'NORMAL')", name='ck_inventory_used_items_sellable_grade'),
    sa.CheckConstraint('(discount_rate IS NULL) = (sale_price IS NULL)', name='ck_inventory_used_items_pricing_pair'),
    sa.CheckConstraint('discount_rate IS NULL OR (discount_rate >= 0 AND discount_rate < 1)', name='ck_inventory_used_items_discount_rate'),
    sa.CheckConstraint('sale_price IS NULL OR sale_price > 0', name='ck_inventory_used_items_sale_price_positive'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['return_job_id'], ['return_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lpn_barcode'),
    sa.UniqueConstraint('return_job_id')
    )
    op.create_table('order_proposals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('return_job_id', sa.Uuid(), nullable=True),
    sa.Column('proposal_source', sa.Enum('RETURN_REJECTION', 'SAFETY_STOCK', name='restockproposalsource'), nullable=False),
    sa.Column('recent_sales_quantity', sa.Integer(), nullable=False),
    sa.Column('current_stock', sa.Integer(), nullable=False),
    sa.Column('pending_auto_po_quantity', sa.Integer(), nullable=False),
    sa.Column('rejected_quantity', sa.Integer(), nullable=False),
    sa.Column('rejection_reason_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recommended_order_quantity', sa.Integer(), nullable=False),
    sa.Column('reason_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risk_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'NOT_REQUIRED', name='orderproposalstatus'), nullable=False),
    sa.Column('auto_po_order_id', sa.Uuid(), nullable=True),
    sa.Column('reviewer_id', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_comment', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('pending_auto_po_quantity >= 0', name='ck_order_proposals_pending_auto_po_nonnegative'),
    sa.ForeignKeyConstraint(['auto_po_order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['return_job_id'], ['return_jobs.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('return_job_id', name='uq_order_proposals_return_job')
    )
    op.create_index(op.f('ix_order_proposals_auto_po_order_id'), 'order_proposals', ['auto_po_order_id'], unique=False)
    op.create_index(op.f('ix_order_proposals_book_id'), 'order_proposals', ['book_id'], unique=False)
    op.create_index(op.f('ix_order_proposals_proposal_source'), 'order_proposals', ['proposal_source'], unique=False)
    op.create_index(op.f('ix_order_proposals_return_job_id'), 'order_proposals', ['return_job_id'], unique=False)
    op.create_index(op.f('ix_order_proposals_reviewer_id'), 'order_proposals', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_order_proposals_status'), 'order_proposals', ['status'], unique=False)
    op.create_index(op.f('ix_order_proposals_tenant_id'), 'order_proposals', ['tenant_id'], unique=False)
    op.create_table('rejected_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('inbound_item_id', sa.Uuid(), nullable=False),
    sa.Column('return_job_id', sa.Uuid(), nullable=True),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('lpn_barcode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ubci_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('rejection_reason', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('REJECT_HOLD', 'DISCARDED', name='rejecteditemstatus'), nullable=False),
    sa.Column('rejected_at', sa.DateTime(), nullable=False),
    sa.Column('discarded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['inbound_item_id'], ['inbound_items.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['return_job_id'], ['return_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inbound_item_id'),
    sa.UniqueConstraint('lpn_barcode'),
    sa.UniqueConstraint('return_job_id')
    )
    op.create_index('ix_rejected_items_status_location', 'rejected_items', ['status', 'location_id'], unique=False)
    op.create_table('order_item_lpn_allocations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_item_id', sa.Uuid(), nullable=False),
    sa.Column('inventory_used_item_id', sa.Uuid(), nullable=False),
    sa.Column('picked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_used_item_id'], ['inventory_used_items.id'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_item_id', 'inventory_used_item_id', name='uq_order_item_lpn_allocation')
    )
    op.create_index(op.f('ix_order_item_lpn_allocations_order_item_id'), 'order_item_lpn_allocations', ['order_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema changes."""
    raise RuntimeError(
        "Downgrading below the Alembic baseline is blocked because it would "
        "delete all application tables. Restore a verified database backup "
        "instead."
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_item_lpn_allocations_order_item_id'), table_name='order_item_lpn_allocations')
    op.drop_table('order_item_lpn_allocations')
    op.drop_index('ix_rejected_items_status_location', table_name='rejected_items')
    op.drop_table('rejected_items')
    op.drop_index(op.f('ix_order_proposals_tenant_id'), table_name='order_proposals')
    op.drop_index(op.f('ix_order_proposals_status'), table_name='order_proposals')
    op.drop_index(op.f('ix_order_proposals_reviewer_id'), table_name='order_proposals')
    op.drop_index(op.f('ix_order_proposals_return_job_id'), table_name='order_proposals')
    op.drop_index(op.f('ix_order_proposals_proposal_source'), table_name='order_proposals')
    op.drop_index(op.f('ix_order_proposals_book_id'), table_name='order_proposals')
    op.drop_index(op.f('ix_order_proposals_auto_po_order_id'), table_name='order_proposals')
    op.drop_table('order_proposals')
    op.drop_table('inventory_used_items')
    op.drop_table('boards')
    op.drop_index(op.f('ix_return_jobs_tenant_id'), table_name='return_jobs')
    op.drop_table('return_jobs')
    op.drop_index(op.f('ix_order_item_inventory_allocations_order_item_id'), table_name='order_item_inventory_allocations')
    op.drop_index(op.f('ix_order_item_inventory_allocations_inventory_id'), table_name='order_item_inventory_allocations')
    op.drop_table('order_item_inventory_allocations')
    op.drop_index(op.f('ix_notification_recipients_user_id'), table_name='notification_recipients')
    op.drop_index(op.f('ix_notification_recipients_read_at'), table_name='notification_recipients')
    op.drop_index(op.f('ix_notification_recipients_notification_id'), table_name='notification_recipients')
    op.drop_table('notification_recipients')
    op.drop_table('board_posts')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_refresh_token_expires_at'), table_name='users')
    op.drop_index(op.f('ix_users_employee_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_notifications_tenant_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('inventory_logs')
    op.drop_table('inventory')
    op.drop_table('inbound_items')
    op.drop_index(op.f('ix_fds_reports_tenant_id'), table_name='fds_reports')
    op.drop_table('fds_reports')
    op.drop_table('weekly_insights')
    op.drop_index(op.f('ix_tenants_code'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_orders_waybill_number'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('locations')
    op.drop_table('inbound_jobs')
    op.drop_table('fds_policies')
    op.drop_table('books')

    enum_names = (
        'bookcategory',
        'conditiongrade',
        'inboundstatus',
        'inboundtype',
        'inspectionmode',
        'inventorytransactiontype',
        'notificationcategory',
        'notificationseverity',
        'orderproposalstatus',
        'orderstatus',
        'ordertype',
        'postcategory',
        'rejecteditemstatus',
        'restockproposalsource',
        'returnjobstatus',
        'standardsize',
        'ticketstatus',
        'usedinventorystatus',
        'userrole',
        'userstatus',
    )
    for enum_name in enum_names:
        postgresql.ENUM(name=enum_name).drop(
            op.get_bind(),
            checkfirst=True,
        )
    # ### end Alembic commands ###
